# Generated by Django 3.1.7 on 2021-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210318_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='noimg.jpg', upload_to='posts_images'),
        ),
    ]
