# Generated by Django 3.1.7 on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow_on',
            field=models.IntegerField(),
        ),
    ]
