# Generated by Django 3.1.7 on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentBy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentOn',
            field=models.IntegerField(),
        ),
    ]
